[tool.poetry]
name = "intro-to-python"
version = "0.5.0"
description = "An introduction to Python and programming for wanna-be data scientists"
authors = ["Alexander Hess <alexander@webartifex.biz>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
jupyter = "^1.0"
numpy = "^1.17"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
blackcellmagic = "^0.0.2"
jupyter-contrib-nbextensions = "^0.5"
rise = "^5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
